# Generated by Django 5.2.4 on 2025-07-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Pet Owner Profile', 'verbose_name_plural': 'Pet Owner Profiles'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_vet_admin',
            field=models.BooleanField(default=False, help_text='Check if this user is a veterinarian/admin'),
        ),
    ]
