# Generated by Django 5.2.4 on 2025-09-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='pet',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='species',
        ),
        migrations.AddField(
            model_name='pet',
            name='animal_type',
            field=models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog'), ('hamster', 'Hamster'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('fish', 'Fish'), ('other', 'Other')], default='dog', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pets/'),
        ),
        migrations.AddField(
            model_name='pet',
            name='medical_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='dog', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.PositiveIntegerField(help_text='Age in years'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True),
        ),
    ]
