# Generated by Django 6.0 on 2026-01-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='blood_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='chronic_disease',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='spayed_neutered',
            field=models.BooleanField(default=False),
        ),
    ]
