# Generated by Django 5.2.4 on 2025-09-20 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_conversation_is_archived'),
        ('pets', '0002_alter_pet_options_remove_pet_date_of_birth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(default='', max_length=50, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('symptoms_text', models.TextField(help_text="User's symptom description")),
                ('image_analysis', models.JSONField(blank=True, help_text='Image classification results', null=True)),
                ('ml_predictions', models.JSONField(help_text='Random Forest predictions')),
                ('ai_explanation', models.TextField(help_text='Gemini AI explanation')),
                ('suggested_diagnoses', models.JSONField(help_text='Structured diagnosis suggestions')),
                ('overall_severity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('urgency_level', models.CharField(choices=[('routine', 'Routine Check-up'), ('soon', 'Schedule Soon'), ('immediate', 'Immediate Care'), ('emergency', 'Emergency')], max_length=20)),
                ('pet_context', models.JSONField(help_text='Pet profile context used')),
                ('confidence_score', models.FloatField(default=0.0)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_diagnoses', to='pets.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_diagnoses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=200)),
                ('likelihood_percentage', models.FloatField()),
                ('description', models.TextField()),
                ('matched_symptoms', models.JSONField(help_text='List of symptoms that match this condition')),
                ('urgency_level', models.CharField(choices=[('routine', 'Routine Check-up'), ('soon', 'Schedule Soon'), ('immediate', 'Immediate Care'), ('emergency', 'Emergency')], max_length=20)),
                ('contagious', models.BooleanField(default=False)),
                ('treatment_notes', models.TextField(blank=True, null=True)),
                ('confidence_score', models.FloatField()),
                ('risk_factors', models.JSONField(blank=True, help_text='Risk factors for this condition', null=True)),
                ('ai_diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='chatbot.aidiagnosis')),
            ],
            options={
                'ordering': ['-likelihood_percentage'],
            },
        ),
    ]
