# Generated by Django 5.2.4 on 2025-09-28 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_add_ai_diagnosis_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='aidiagnosis',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='symptom_images/'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='animal_type',
            field=models.CharField(default='dog', max_length=20),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to=settings.AUTH_USER_MODEL),
        ),
    ]
