# Generated by Django 5.2.4 on 2025-09-28 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_diagnosis_options_aidiagnosis_uploaded_image_and_more'),
        ('pets', '0002_alter_pet_options_remove_pet_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='pets.pet'),
        ),
    ]
