# Generated by Django 5.2.4 on 2025-09-28 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_conversation_pet'),
    ]

    operations = [
    ]
