# Generated by Django 5.2.4 on 2025-10-31 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_add_pinned_archived_fields'),
        ('pets', '0002_alter_pet_options_remove_pet_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOAPReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=30, unique=True)),
                ('subjective', models.TextField()),
                ('objective', models.JSONField()),
                ('assessment', models.JSONField()),
                ('plan', models.JSONField()),
                ('flag_level', models.CharField(max_length=20)),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
                ('date_flagged', models.DateTimeField(auto_now_add=True)),
                ('chat_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soap_reports', to='chatbot.conversation')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soap_reports', to='pets.pet')),
            ],
            options={
                'ordering': ['-date_generated'],
            },
        ),
    ]
