# Generated by Django 5.2.4 on 2025-11-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_soapreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aidiagnosis',
            name='uploaded_image',
        ),
    ]
