# Generated by Django 5.2.4 on 2025-11-17 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_remove_aidiagnosis_uploaded_image'),
        ('pets', '0002_alter_pet_options_remove_pet_date_of_birth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_date', models.DateTimeField(auto_now_add=True)),
                ('symptom_date', models.DateField(help_text='Actual date symptoms occurred')),
                ('symptoms', models.JSONField(help_text="List of symptom names. Example: ['vomiting', 'lethargy', 'loss_of_appetite']")),
                ('overall_severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], help_text='Overall severity of symptoms', max_length=20)),
                ('symptom_details', models.JSONField(blank=True, default=dict, help_text="Symptom-specific details. Example: {'vomiting': {'count': 3, 'notes': 'After eating'}}")),
                ('compared_to_yesterday', models.CharField(blank=True, choices=[('worse', 'Getting Worse'), ('same', 'About the Same'), ('better', 'Getting Better'), ('new', 'First Occurrence')], help_text='How symptoms compare to previous day', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional observations or context')),
                ('risk_score', models.IntegerField(default=0, help_text='Calculated risk score (0-100)')),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], help_text='Calculated risk level based on score', max_length=20)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_logs', to='pets.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Symptom Log',
                'verbose_name_plural': 'Symptom Logs',
                'ordering': ['-symptom_date', '-logged_date'],
            },
        ),
        migrations.CreateModel(
            name='SymptomAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('rapid_deterioration', 'Rapid Deterioration'), ('new_critical_symptom', 'New Critical Symptom'), ('prolonged_symptoms', 'Prolonged Symptoms'), ('risk_escalation', 'Risk Level Increased')], help_text='Type of alert triggered', max_length=50)),
                ('alert_message', models.TextField(help_text='Detailed alert message for the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False, help_text='Whether the user has acknowledged this alert')),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When the alert was acknowledged', null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_alerts', to='pets.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_alerts', to=settings.AUTH_USER_MODEL)),
                ('symptom_log', models.ForeignKey(help_text='The symptom log that triggered this alert', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='chatbot.symptomlog')),
            ],
            options={
                'verbose_name': 'Symptom Alert',
                'verbose_name_plural': 'Symptom Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='symptomlog',
            index=models.Index(fields=['pet', '-symptom_date'], name='chatbot_sym_pet_id_4ed451_idx'),
        ),
        migrations.AddIndex(
            model_name='symptomlog',
            index=models.Index(fields=['user', '-logged_date'], name='chatbot_sym_user_id_29ef03_idx'),
        ),
    ]
