# Generated by Django 5.2.4 on 2025-12-01 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_symptomlog_symptomalert_and_more'),
        ('pets', '0002_alter_pet_options_remove_pet_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetHealthTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('risk_score', models.IntegerField(default=0, help_text='Risk score from 0-100')),
                ('urgency_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=20)),
                ('trend_analysis', models.TextField(help_text='AI explanation of the trend')),
                ('prediction', models.TextField(help_text='AI forecast for next 24h')),
                ('alert_needed', models.BooleanField(default=False, help_text='Whether an alert should be shown')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_trends', to='pets.pet')),
            ],
            options={
                'verbose_name': 'Pet Health Trend',
                'verbose_name_plural': 'Pet Health Trends',
                'ordering': ['-analysis_date'],
                'indexes': [models.Index(fields=['pet', '-analysis_date'], name='chatbot_pet_pet_id_bd6503_idx')],
            },
        ),
    ]
