# Generated by Django 6.0 on 2025-12-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_pethealthtrend'),
    ]

    operations = [
        migrations.AddField(
            model_name='soapreport',
            name='verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soapreport',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified by Vet'), ('flagged', 'Flagged for Review')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='soapreport',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
