# Generated by Django 6.0 on 2025-12-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_soapreport_verification_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soapreport',
            name='verification_status',
            field=models.CharField(choices=[('not_verified', 'Not Verified'), ('verified', 'Verified by Vet'), ('flagged', 'Flagged for Review')], default='pending', max_length=20),
        ),
    ]
