# Generated by Django 5.2.4 on 2025-11-01 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('MASTER', 'Master Admin'), ('VET', 'Veterinarian'), ('DESK', 'Front Desk')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('profile_image', models.ImageField(blank=True, help_text='Admin profile picture', null=True, upload_to='admin_profiles/')),
                ('recovery_email', models.EmailField(blank=True, help_text='Email for password recovery', max_length=254, null=True)),
                ('clinic_info', models.CharField(blank=True, help_text='Clinic or organization information', max_length=255, null=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('password_updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'db_table': 'admins',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='admins_email_fe9722_idx'), models.Index(fields=['role'], name='admins_role_baf3bc_idx'), models.Index(fields=['is_active'], name='admins_is_acti_5d7c65_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminPasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to='admin_panel.admin')),
            ],
            options={
                'verbose_name': 'Admin Password History',
                'verbose_name_plural': 'Admin Password Histories',
                'db_table': 'admin_password_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', '-created_at'], name='admin_passw_admin_i_eab083_idx')],
            },
        ),
    ]
