# Generated by Django 5.2.4 on 2025-11-02 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_admin_adminpasswordhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('STATUS_CHANGE', 'Status Changed'), ('ROLE_CHANGE', 'Role Changed'), ('EMAIL_CHANGE', 'Email Changed')], max_length=20)),
                ('target_admin_id', models.CharField(help_text='ID of the admin account that was acted upon', max_length=100)),
                ('target_admin_email', models.EmailField(blank=True, help_text='Email of the admin account that was acted upon', max_length=254, null=True)),
                ('details', models.JSONField(default=dict, help_text='Additional details about the action')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admin Audit Log',
                'verbose_name_plural': 'Admin Audit Logs',
                'db_table': 'admin_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='announcement_type',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='content',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='target_audience',
        ),
        migrations.AddField(
            model_name='admin',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag for audit purposes'),
        ),
        migrations.AddField(
            model_name='admin',
            name='recovery_email_verified',
            field=models.BooleanField(default=False, help_text='Whether the recovery email has been verified'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='description',
            field=models.TextField(default='No description provided', help_text='Announcement description (max 500 characters)', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='icon_type',
            field=models.CharField(choices=[('vaccination', 'Vaccination'), ('wellness', 'Wellness'), ('welcome', 'Welcome'), ('general', 'General')], default='general', help_text='Icon type for display', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Expiration date (null = ongoing/never expires)', null=True),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin who created this announcement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='admin_panel.admin'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether announcement is currently active'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(help_text='Announcement title (max 100 characters)', max_length=100),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_active', '-created_at'], name='announcemen_is_acti_da44f2_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['valid_until'], name='announcemen_valid_u_3e5bc9_idx'),
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='admin',
            field=models.ForeignKey(blank=True, help_text='Admin who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='admin_panel.admin'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['admin', '-timestamp'], name='admin_audit_admin_i_3ece08_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['target_admin_id'], name='admin_audit_target__42664b_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['action', '-timestamp'], name='admin_audit_action_0bdf0a_idx'),
        ),
    ]
