# Generated by Django 6.0 on 2025-12-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_adminauditlog_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='style',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
