import React from 'react';
import AdminLayout from './AdminLayout';

const AdminReports = () => {
  return (
    <AdminLayout>
      <div className="bg-white shadow rounded-lg p-6">
        <h2 className="text-xl font-semibold mb-4">SOAP Reports</h2>
        <p className="text-gray-600 mb-4">Manage and view all veterinary SOAP reports generated by the AI system.</p>
        
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
          <h3 className="text-lg font-medium text-blue-900 mb-2">Coming Soon</h3>
          <p className="text-blue-700">
            This page will include:
          </p>
          <ul className="list-disc list-inside text-blue-700 mt-2">
            <li>View all SOAP reports</li>
            <li>Filter by pet, date, or severity</li>
            <li>Export reports to PDF</li>
            <li>Flagged case management</li>
            <li>Report analytics and insights</li>
          </ul>
        </div>
      </div>
    </AdminLayout>
  );
};

export default AdminReports;