"""
Standard error codes for PawPal API
All error codes are string constants for consistent error handling across the application
"""

# ============= Authentication Errors (401) =============
AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED"
AUTH_REQUIRED = "AUTH_REQUIRED"
AUTH_ACCOUNT_INACTIVE = "ACCOUNT_INACTIVE"

# ============= Authorization Errors (403) =============
PERMISSION_DENIED = "PERMISSION_DENIED"
ROLE_REQUIRED = "ROLE_REQUIRED"
RESOURCE_FORBIDDEN = "RESOURCE_FORBIDDEN"
INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS"

# ============= Validation Errors (400) =============
VALIDATION_ERROR = "VALIDATION_ERROR"
MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
INVALID_FORMAT = "INVALID_FORMAT"
INVALID_INPUT = "INVALID_INPUT"
FIELD_REQUIRED = "FIELD_REQUIRED"
FIELD_TOO_LONG = "FIELD_TOO_LONG"
FIELD_TOO_SHORT = "FIELD_TOO_SHORT"
INVALID_EMAIL = "INVALID_EMAIL"
INVALID_PHONE = "INVALID_PHONE"
INVALID_DATE = "INVALID_DATE"
INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
FILE_TOO_LARGE = "FILE_TOO_LARGE"

# ============= Resource Errors (404) =============
RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
USER_NOT_FOUND = "USER_NOT_FOUND"
PET_NOT_FOUND = "PET_NOT_FOUND"
ADMIN_NOT_FOUND = "ADMIN_NOT_FOUND"
CONVERSATION_NOT_FOUND = "CONVERSATION_NOT_FOUND"
ANNOUNCEMENT_NOT_FOUND = "ANNOUNCEMENT_NOT_FOUND"

# ============= Business Logic Errors (422) =============
OTP_EXPIRED = "OTP_EXPIRED"
OTP_INVALID = "OTP_INVALID"
OTP_MAX_ATTEMPTS = "OTP_MAX_ATTEMPTS"
EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED"
CANNOT_DELETE_LAST_ADMIN = "CANNOT_DELETE_LAST_ADMIN"
PASSWORD_REUSE_NOT_ALLOWED = "PASSWORD_REUSE_NOT_ALLOWED"
PASSWORD_TOO_WEAK = "PASSWORD_TOO_WEAK"
RECOVERY_EMAIL_SAME_AS_PRIMARY = "RECOVERY_EMAIL_SAME_AS_PRIMARY"
VERIFICATION_TOKEN_EXPIRED = "VERIFICATION_TOKEN_EXPIRED"
VERIFICATION_TOKEN_INVALID = "VERIFICATION_TOKEN_INVALID"

# ============= Rate Limiting Errors (429) =============
RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS"
OTP_RATE_LIMIT = "OTP_RATE_LIMIT"

# ============= Server Errors (500) =============
INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
EMAIL_SEND_FAILED = "EMAIL_SEND_FAILED"
FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
DATABASE_ERROR = "DATABASE_ERROR"
EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"

